#!/usr/bin/php
<?php

$html = file_get_contents("template.html");
$pattern = "|<!-- split:(.*) -->|U";

preg_match_all($pattern, $html, $matches, PREG_SET_ORDER);

$split = preg_split($pattern, $html);

$tmp = array();
foreach($matches as $key => $value) {
  if(!array_key_exists($value[1], $tmp)) {
    $tmp[$value[1]] = addslashes(trimContent($split[$key + 1]));
  }
} 

function trimContent($str) {
  $arr = explode("\n",$str);
  $output = "";
  foreach($arr as $line) {
    $output .= trim($line);
  }
  return $output;
}

$fp = fopen("../src/html.h", "w");
fputs($fp, "#ifndef html_h\n");
fputs($fp, "#define html_h\n");
fputs($fp, "\n");
foreach($tmp as $header => $content) {
  $header = strtoupper($header);
  fputs ($fp, "const char HTML_${header}[] PROGMEM = \"$content\";\n");
}
fputs($fp, "\n");
fputs($fp, "#endif\n");
fclose ($fp);
