#ifndef html_h
#define html_h

const char HTML_HEADER[] PROGMEM = "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Device Info - {device_id}</title><link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\"><link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\"></head><body><script type=\"application/javascript\">function sendValue(input) {$.ajax({url: input.dataset.url, method: \"POST\", data: $(input).closest(\"form\").find(\"input\").val()}).complete(function (data, textStatus, jqXHR) {alert(textStatus);})}</script><div class=\"container\"><h1>Device Info - {device_id}</h1><ul class=\"nav nav-tabs\" role=\"tablist\"><li role=\"presentation\" class=\"active\"><a href=\"#devices\" aria-controls=\"devices\" role=\"tab\" data-toggle=\"tab\"><span class=\"glyphicon glyphicon-dashboard\" aria-hidden=\"true\"></span> Devices</a></li><li role=\"presentation\"><a href=\"#input\" aria-controls=\"input\" role=\"tab\" data-toggle=\"tab\"><span class=\"glyphicon glyphicon-pencil\" aria-hidden=\"true\"></span> Input</a></li><li role=\"presentation\"><a href=\"#config\" aria-controls=\"config\" role=\"tab\" data-toggle=\"tab\"><span class=\"glyphicon glyphicon-cog\" aria-hidden=\"true\"></span> Config</a></li><li role=\"presentation\"><a href=\"#about\" aria-controls=\"about\" role=\"tab\" data-toggle=\"tab\"><span class=\"glyphicon glyphicon-book\" aria-hidden=\"true\"></span> About</a></li></ul><div class=\"tab-content\" style=\"border-style: solid; border-color: #ddd; border-width: 0px 1px 1px 1px\"><div role=\"tabpanel\" class=\"tab-pane active\" id=\"devices\"><br /><div class=\"container-fluid\"><div class=\"row\">";
const char HTML_SENSOR[] PROGMEM = "<div class=\"col-md-4\"><div class=\"panel panel-info\"><div class=\"panel-heading\"><strong>{name}</strong></div><div class=\"panel-body\" style=\"font-size: 24px;\">{value}</div><div class=\"panel-footer\" style=\"padding: 5px 15px; font-size: 85%\"><strong>Last updated:</strong> {last_updated}</div></div></div>";
const char HTML_VALUE_ON[] PROGMEM = "<span class=\"label label-success\">{value}</span>";
const char HTML_VALUE_OFF[] PROGMEM = "<span class=\"label label-danger\">{value}</span>";
const char HTML_INPUT_PANEL[] PROGMEM = "</div></div></div><div role=\"tabpanel\" class=\"tab-pane\" id=\"input\"><br /><div class=\"container-fluid\"><div class=\"row\">";
const char HTML_INPUT[] PROGMEM = "<div class=\"col-md-4\"><div class=\"panel panel-success\"><div class=\"panel-heading\"><strong>{name}</strong></div><div class=\"panel-body\" style=\"font-size: 24px;\"><form><div class=\"input-group\"><input type=\"text\" class=\"form-control\" placeholder=\"value\"><span class=\"input-group-btn\"><button class=\"btn btn-default\" type=\"button\" data-url=\"{name}\" onclick=\"sendValue(this);\">Send</button></span></div></form></div></div></div>";
const char HTML_FOOTER1[] PROGMEM = "</div></div></div><div role=\"tabpanel\" class=\"tab-pane\" id=\"config\"><br /><div class=\"container-fluid\"><div class=\"row\"><div class=\"col-md-12\"><div class=\"alert alert-warning\" role=\"alert\"><strong>Warning!</strong> Not connected to WiFi</div><form class=\"form-horizontal\"><h3>WiFi</h3><hr/><div class=\"form-group\"><label for=\"inputEmail3\" class=\"col-sm-2 control-label\">Email</label><div class=\"col-sm-8\"><input type=\"email\" class=\"form-control\" id=\"inputEmail3\" placeholder=\"Rssd\"></div></div><div class=\"form-group\"><label for=\"inputEmail3\" class=\"col-sm-2 control-label\">Password</label><div class=\"col-sm-8\"><input type=\"password\" class=\"form-control\" id=\"inputPassword\" placeholder=\"Password\"></div></div></br><h3>MQTT</h3><hr/><div class=\"form-group\"><label for=\"inputUsername\" class=\"col-sm-2 control-label\">Username</label><div class=\"col-sm-8\"><input type=\"text\" class=\"form-control\" id=\"inputUsername\" placeholder=\"Username\"></div></div><div class=\"form-group\"><label for=\"inputPassword\" class=\"col-sm-2 control-label\">Password</label><div class=\"col-sm-8\"><input type=\"password\" class=\"form-control\" id=\"inputPassword\" placeholder=\"Password\"></div></div><!--</br><h3>Other</h3><hr/><div class=\"form-group\"><label for=\"inputFoo\" class=\"col-sm-2 control-label\">Foo</label><div class=\"col-sm-8\"><input type=\"text\" class=\"form-control\" id=\"inputFoo\" placeholder=\"Foo\"></div></div>--><hr/><div class=\"form-group\"><div class=\"col-sm-offset-9 col-sm-2\"><button type=\"submit\" class=\"btn btn-default\">Save</button></div></div></form></div></div></div></div><div role=\"tabpanel\" class=\"tab-pane\" id=\"about\"><br /><div class=\"container-fluid\"><div class=\"row\"><div class=\"col-md-12\"><p>Device is using EasyMqtt version 0.0.1</p>Device Id: {device_id}<br />Topic: {topic}<br /><hr />Rest API:<br /><ul>";
const char HTML_REST_DOC[] PROGMEM = "<li>{path}</li>";
const char HTML_FOOTER2[] PROGMEM = "</ul></div></div></div></div></div></div><script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script><script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script></body></html>";

#endif
